-- MySQL Script generated by MySQL Workbench
-- lun 08 feb 2021 19:55:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Privileges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Privileges` (
  `Type_of_privilege` VARCHAR(45) NULL,
  `Code` INT NOT NULL,
  PRIMARY KEY (`Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUser` INT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `e-mail` VARCHAR(60) NOT NULL,
  `Privileges` INT NOT NULL,
  `Date of birth` DATE NULL,
  INDEX `fk_Users_Privileges_idx` (`Privileges` ASC) VISIBLE,
  PRIMARY KEY (`idUser`),
  CONSTRAINT `fk_Users_Privileges`
    FOREIGN KEY (`Privileges`)
    REFERENCES `mydb`.`Privileges` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Followers` (
  `idFollows` INT NOT NULL AUTO_INCREMENT,
  `FollowedID` INT NULL,
  `FollowerID` INT NULL,
  PRIMARY KEY (`idFollows`),
  INDEX `fk_Followers_1_idx` (`FollowedID` ASC, `FollowerID` ASC) VISIBLE,
  CONSTRAINT `fk_Followers_1`
    FOREIGN KEY (`FollowedID` , `FollowerID`)
    REFERENCES `mydb`.`Users` (`Username` , `Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Posts` (
  `idPosts` INT NOT NULL AUTO_INCREMENT,
  `UserID` VARCHAR(45) NULL,
  `Title` VARCHAR(300) NULL,
  `Description` TEXT(5000) NULL,
  `Likes` INT NULL,
  `Dislikes` INT NULL,
  `Section` ENUM('UserPost', 'ForumPost') NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`idPosts`),
  INDEX `fk_Posts_1_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `fk_Posts_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`Users` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comments` (
  `idComments` INT NOT NULL,
  `PostID` INT NULL,
  `Content` TEXT(3000) NULL,
  `Likes` INT NULL,
  `Dislikes` INT NULL,
  `UserID` INT NOT NULL,
  `Date` INT NULL,
  PRIMARY KEY (`idComments`),
  INDEX `fk_Comments_Posts1_idx` (`PostID` ASC) VISIBLE,
  INDEX `fk_Comments_Users1_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `fk_Comments_Posts1`
    FOREIGN KEY (`PostID`)
    REFERENCES `mydb`.`Posts` (`idPosts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Users1`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Journal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Journal` (
  `idJournal` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(60) NULL,
  `Publication date` DATE NULL,
  `NewsID` VARCHAR(45) NULL,
  PRIMARY KEY (`idJournal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categories` (
  `idCategories` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`News`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`News` (
  `idNews` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(300) NULL,
  `Subtitle` VARCHAR(300) NULL,
  `URL` VARCHAR(100) NULL,
  `Category` INT NULL,
  `JournalID` INT NULL,
  PRIMARY KEY (`idNews`),
  INDEX `fk_News_Journal1_idx` (`JournalID` ASC) VISIBLE,
  INDEX `fk_News_Categories1_idx` (`Category` ASC) VISIBLE,
  CONSTRAINT `fk_News_Journal1`
    FOREIGN KEY (`JournalID`)
    REFERENCES `mydb`.`Journal` (`idJournal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_News_Categories1`
    FOREIGN KEY (`Category`)
    REFERENCES `mydb`.`Categories` (`idCategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Authors` (
  `idAuthors` INT NOT NULL AUTO_INCREMENT,
  `Full_name` VARCHAR(45) NULL,
  `Institution` VARCHAR(45) NULL,
  `NewsID` INT NULL,
  PRIMARY KEY (`idAuthors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Authors_has_News`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Authors_has_News` (
  `Authors_idAuthors` INT NOT NULL,
  `News_idNews` INT NOT NULL,
  PRIMARY KEY (`Authors_idAuthors`, `News_idNews`),
  INDEX `fk_Authors_has_News_News1_idx` (`News_idNews` ASC) VISIBLE,
  INDEX `fk_Authors_has_News_Authors1_idx` (`Authors_idAuthors` ASC) VISIBLE,
  CONSTRAINT `fk_Authors_has_News_Authors1`
    FOREIGN KEY (`Authors_idAuthors`)
    REFERENCES `mydb`.`Authors` (`idAuthors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Authors_has_News_News1`
    FOREIGN KEY (`News_idNews`)
    REFERENCES `mydb`.`News` (`idNews`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Answers` (
  `idAnswers` INT NOT NULL,
  `UserID` INT NULL,
  `PostID` INT NULL,
  `Title` VARCHAR(250) NULL,
  `Content` TEXT(5000) NULL,
  `Date` INT NULL,
  PRIMARY KEY (`idAnswers`),
  INDEX `fk_Answers_Posts1_idx` (`PostID` ASC) VISIBLE,
  CONSTRAINT `fk_Answers_Posts1`
    FOREIGN KEY (`PostID`)
    REFERENCES `mydb`.`Posts` (`idPosts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ratings` (
  `idRatings` INT NOT NULL,
  `AnswerID` INT NULL,
  `Stars` INT NULL,
  `UserID` INT NULL,
  PRIMARY KEY (`idRatings`),
  INDEX `fk_Ratings_Answers1_idx` (`AnswerID` ASC) VISIBLE,
  CONSTRAINT `fk_Ratings_Answers1`
    FOREIGN KEY (`AnswerID`)
    REFERENCES `mydb`.`Answers` (`idAnswers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
